import FuturePage, { LocationsPage } from '@/pages/future';

export const Menus = () => <FuturePage title="Menus" description="Manage the menus and versions that shape the operation." />;
export const MenuPlanning = () => <FuturePage title="Menu planning" description="Plan the service periods, menus, and operating units that shape demand." />;
export const Recipes = () => <FuturePage title="Recipes" description="Connect recipe definitions to ingredient cost and portion logic." />;
export const RecipeDetail = () => <FuturePage title="Recipe detail" description="Recipe detail will connect ingredients, yields, and costing when the menu service is available." eyebrow="Menu Engineering / Recipes" />;
export const Ingredients = () => <FuturePage title="Ingredients" description="Maintain the material language used across recipes, procurement, and stock." />;
export const Costing = () => <FuturePage title="Costing" description="See how current ingredient prices flow into menu cost." />;
export const PortionPlanning = () => <FuturePage title="Portion planning" description="Plan yields and portions with operational clarity." />;
export const DemandForecast = () => <FuturePage title="Demand forecast" description="Prepare future demand views for a connected planning service." />;
export const MenuPerformance = () => <FuturePage title="Menu performance" description="Compare menu performance once the analytics connection is available." />;
export const StockOverview = () => <FuturePage title="Stock overview" description="See current stock position across your operating units." />;
export const InventoryCount = () => <FuturePage title="Inventory count" description="Prepare count sessions and reconcile what is physically on hand." />;
export const InventoryCountDetail = () => <FuturePage title="Count session" description="Count session detail will connect to the inventory ledger when the endpoint is available." eyebrow="Inventory / Count" />;
export const StockAdjustments = () => <FuturePage title="Stock adjustments" description="Review controlled adjustments to the stock ledger." />;
export const StockTransfers = () => <FuturePage title="Stock transfers" description="Internal Transfers are available at Inventory → Internal Transfers." />;
export const GoodsReceiptPlaceholder = () => <FuturePage title="Goods Receipt" description="Goods receipt posting remains on Receiving / GRN. This inventory navigation item is reserved for the next inventory posting phase." eyebrow="Inventory / Goods Receipt" />;
export const InventoryTransactions = () => <FuturePage title="Inventory Transactions" description="The location-based inventory ledger is live for Internal Transfers. A full transaction browser for GR, GI, waste, and count adjustments is reserved for the next phase." eyebrow="Inventory / Transactions" />;
export const GoodsIssue = () => <FuturePage title="Goods issue" description="Record controlled issues from stores to the operation." />;
export const DamageWriteOff = () => <FuturePage title="Damage / write-off" description="Keep damage and write-off activity visible and accountable." />;
export const BatchExpiry = () => <FuturePage title="Batch & expiry" description="Monitor batch identity and expiry exposure." />;
export const Receive = () => <FuturePage title="Receive" description="Prepare the receiving workspace for delivery checks and receipt posting." />;
export const ReceivingExceptions = () => <FuturePage title="Receiving exceptions" description="Surface mismatches that need operational attention." />;
export const MaterialRequirements = () => <FuturePage title="Material requirements" description="Turn operating demand into a connected procurement requirement." />;
export const PurchaseSuggestions = () => <FuturePage title="Purchase suggestions" description="Review suggested orders once procurement recommendations are connected." />;
export const SupplierComparison = () => <FuturePage title="Supplier comparison" description="Compare supplier terms and operating decisions in one view." />;
export const ReorderPlanning = () => <FuturePage title="Reorder planning" description="Plan replenishment against stock and demand signals." />;
export const DocumentInbox = () => <FuturePage title="Document inbox" description="Triage incoming operational documents." />;
export const InvoiceCapture = () => <FuturePage title="Invoice capture" description="Capture invoices from connected sources." />;
export const DeliveryNotes = () => <FuturePage title="Delivery notes" description="Keep delivery documentation close to receipt activity." />;
export const ExtractionResults = () => <FuturePage title="OCR / extraction results" description="Review structured document extraction results." />;
export const Extraction = () => <FuturePage title="Extraction" description="Review document extraction readiness and structured results." />;
export const DocumentArchive = () => <FuturePage title="Document archive" description="Find the operational documents that have already been processed." />;
export const Approvals = () => <FuturePage title="Approvals" description="Review decisions waiting for the right operational owner." />;
export const Analytics = () => <FuturePage title="Analytics" description="A measured view of operating performance is being connected." />;
export const MasterData = () => <FuturePage title="Master data" description="The shared reference model for hospitality operations." />;
export const Materials = () => <FuturePage title="Materials" description="Maintain the material catalogue used by purchasing and inventory." />;
export const MasterIngredients = () => <FuturePage title="Ingredients" description="Maintain ingredient references used by recipes and menu planning." />;
export const MasterRecipes = () => <FuturePage title="Recipes" description="Maintain the recipe reference model for hospitality operations." />;
export const MenuItems = () => <FuturePage title="Menu items" description="Maintain menu item references across operating units." />;
export const Suppliers = () => <FuturePage title="Suppliers" description="Maintain supplier references and purchasing relationships." />;
export const UnitsOfMeasure = () => <FuturePage title="Units of measure" description="Keep quantity and conversion references consistent." />;
export const Categories = () => <FuturePage title="Categories" description="Maintain category references for materials and menus." />;
export const Locations = () => <LocationsPage />;
export const RolesPermissions = () => <FuturePage title="Roles & permissions" description="Inspect the role model that determines Cloud reach." />;
export const DocumentExtraction = () => <FuturePage title="Document extraction" description="Configure invoice extraction providers and review extraction readiness." />;
export const Integrations = () => <FuturePage title="Integrations" description="Connect the services that keep Cloud operational." />;
export { default as Configurations } from '@/pages/configurations';
export const AuditLogs = () => <FuturePage title="Audit logs" description="Trace important changes across the operating model." />;
export const Properties = () => <FuturePage title="Properties" description="Manage property-level operating context and structure." />;