<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Compile only DTOs -->
    <Compile Remove="LoggerManager\**\*.cs" />
    <Compile Remove="ExceptionHandler\**\*.cs" />
  </ItemGroup>

</Project>