// <auto-generated />
using System;
using MasterData.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterData.Infrastructure.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260703072214_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("masterdata")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterData.Domain.Entities.UnspscCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Acronym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acronym");

                    b.Property<long?>("Class")
                        .HasColumnType("bigint")
                        .HasColumnName("class");

                    b.Property<string>("ClassDefinition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("class_definition");

                    b.Property<string>("ClassTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("class_title");

                    b.Property<long?>("Commodity")
                        .HasColumnType("bigint")
                        .HasColumnName("commodity");

                    b.Property<string>("CommodityDefinition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commodity_definition");

                    b.Property<string>("CommodityTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("commodity_title");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_updated");

                    b.Property<long?>("Family")
                        .HasColumnType("bigint")
                        .HasColumnName("family");

                    b.Property<string>("FamilyDefinition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_definition");

                    b.Property<string>("FamilyTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_title");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("Key")
                        .HasColumnType("int")
                        .HasColumnName("key");

                    b.Property<long>("Segment")
                        .HasColumnType("bigint")
                        .HasColumnName("segment");

                    b.Property<string>("SegmentDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("segment_definition");

                    b.Property<string>("SegmentTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("segment_title");

                    b.Property<string>("Synonym")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("synonym");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_unspsc_categories");

                    b.HasIndex("IsActive", "Segment", "Family", "Class", "Commodity")
                        .HasDatabaseName("ix_unspsc_categories_is_active_segment_family_class_commodity");

                    b.ToTable("unspsc_categories", "masterdata");
                });
#pragma warning restore 612, 618
        }
    }
}
