<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
     <ItemGroup>
    <ProjectReference Include="..\Supplier.Application\Supplier.Application.csproj" />
    <ProjectReference Include="..\Supplier.Domain\Supplier.Domain.csproj" />
    <ProjectReference Include="..\..\SharedKernel\SharedKernel.csproj" />
    
  </ItemGroup>

</Project>
